engines:
  rubocop:
    enabled: true
    #checks:
    #  Rubocop/Metrics/ClassLength:
    #    enabled: false
    config:
      languages:
      - ruby:
ratings:
  paths:
  - "**.rb"
exclude_paths:
- "src/public/"
- "**.js"
- "**.css"
- "**.erb"
